# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160409_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
