# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='GalleryItemComment',
        ),
    ]
